// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig} from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // El Prisma CLI carga este archivo fuera de Next.js (sin pasar por
    // src/lib/env.ts), asi que necesita leer process.env directamente.
    url: process.env["DATABASE_URL"],
  },
});
